### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by ArmAgeeda** [Legend-Recalls/genshin-cheat-releases#12]
Good times
Created a new account, went into the game with vert.sync had a stable 60 frames per second, run with the cheat 2-3 hours, out of the game, the next day I come back, she and loaded longer, and the frames fell to 30-45, game settings reduced, not helped, microfreezes have also appeared. HELP!

**Comment by Legend-Recalls** [comment]
is it fine without the cheat?

**Comment by ArmAgeeda** [comment]
Yep

**Comment by Legend-Recalls** [comment]
might aswell join the acrepi server and get help there
