### ISSUE TITLE
v47 gets banned

### ISSUE THREAD

**Issue by SDUBZ** [Legend-Recalls/genshin-cheat-releases#6]
![image](https://user-images.githubusercontent.com/14084377/186656915-b4eba437-5636-4981-81ac-85ce93db29b6.png)

**Comment by Legend-Recalls** [comment]
If u violate it too much yes it will, dont use it on spiral abyss at all, avoid co-op aswell and teapot too

**Comment by SDUBZ** [comment]
i just logged in and got banned with this update
