### ISSUE TITLE
Seems like assembly checksum don't match with version 3.0. It's normal only if you using Chinese version of genshin impact.

### ISSUE THREAD

**Issue by xiaocheng168** [Legend-Recalls/genshin-cheat-releases#7]
The client Chinese area fails to start, jams during the process, and prompts the following

> Seems like assembly checksum don't match with version 3.0. It's normal only if you using Chinese version of genshin impact.

**Comment by Legend-Recalls** [comment]
yeah chinese version has some issues always look forward for updates,see if the latest one fixd it
